'''
图书对象
'''


class Dissertation:
    sid = ''
    fdu_sys_no = ''
    type = ''
    title_cn = ''   
    title_foreign = ''
    isbn = ''
    language = ''
    pages = ''
    category = ''
    source = ''

    discipline_no = ''
    discipline_name = ''
    student_type = ''
    degree = ''
    secrecy_level = ''
    student_no = ''
    author = ''
    school = ''
    department = ''
    profession = ''
    first_tutor_name = ''
    first_tutor_school = ''
    first_tutor_department = ''
    first_tutor_profession = ''
    second_tutor_name = ''
    second_tutor_school = ''
    second_tutor_department = ''
    second_tutor_profession = ''
    complete_time = ''
    oral_time = ''
    keyword_cn = ''
    keyword_foreign = ''
    brief_cn = ''
    brief_foreign = ''
    total_pages = ''
    reference = ''
    reference_count = ''
    subsidize = ''
    open_time = ''
    property_no = ''
    collection_no = ''
    calis_oid = ''
    formate = ''
    create_date =  ''
    doc_id = ''
    full_text = ''
    carrier = ''
    collection_location = ''
    sbm = ''

    def __init__(self):
        pass
        
    